apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: objectstorage.example.org
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: objectstorage
  resources:
    - name: bucket
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            locationConstraint: "" # patched
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: "spec.location"
          toFieldPath: "spec.forProvider.locationConstraint"
        - fromFieldPath: "spec.name"
          toFieldPath: "metadata.name"
