apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: argocd
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
          name: argo-cd-argocd-server
          port:
            number: 80
      path: /argocd
      pathType: Prefix
