apiVersion: v2
name: crossplane
description: A Helm chart to install Crossplane
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: crossplane
    repository: https://charts.crossplane.io/stable
    version: ">=2.0.0 <3.0.0"
    condition: crossplane.enabled
    tags: ["crossplane"]
