---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook
  namespace: guestbook
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          service:
            name: guestbook-helm-guestbook
            port:
              number: 80
        path: /guestbook
        pathType: Prefix
  - host: redesigned-capybara-5gqq65v499376g-443.app.github.dev
    http:
      paths:
      - backend:
          service:
            name: guestbook-helm-guestbook
            port:
              number: 80
        path: /guestbook
        pathType: Prefix