---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook
  namespace: guestbook
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      sub_filter '<head>' '<head><base href="/guestbook/">';
      sub_filter_once on;
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          service:
            name: guestbook-helm-guestbook
            port:
              number: 80
        path: /guestbook(/|$)(.*)
        pathType: ImplementationSpecific
  - host: redesigned-capybara-5gqq65v499376g-443.app.github.dev
    http:
      paths:
      - backend:
          service:
            name: guestbook-helm-guestbook
            port:
              number: 80
        path: /guestbook(/|$)(.*)
        pathType: ImplementationSpecific