---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  generateName: crossplane-basic-
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-policy: BeforeHookCreation
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/managed-by: crossplane-basic
spec:
  forProvider:
    locationConstraint: us-east-1
---
apiVersion: s3.aws.crossplane.io/v1alpha3
kind: BucketPolicy
metadata:
  name: crossplane-basic-policy
spec:
  forProvider:
    region: us-east-1
    bucketNameSelector:
      matchControllerRef: true
      matchLabels:
        app.kubernetes.io/managed-by: crossplane-basic
      policy:
        resolution: Required
        resolve: Always
    policy:
      statements:
        - effect: Allow
          actions:
            - s3:GetObject
          principals:
            - type: AWS
              identifiers:
                - "*"
          resources:
            - "arn:aws:s3:::${bucketName}/*"
