apiVersion: v1
kind: Secret
metadata:
  name: repository-secret
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: '{{ .Values.github.serverUrl }}/{{ .Values.github.repository }}'
  usernname: '{{ .Values.github.user }}'
  password: '{{ .Values.github.token }}'
