FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN wget -q https://kcl-lang.io/script/install-cli.sh -O - | /bin/bash && \
    wget -q https://kcl-lang.io/script/install-kcl-lsp.sh -O - | /bin/bash
