apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

# kubeadm patches set kube-apiserver flags for a predictable service-account issuer
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      apiVersion: kind.x-k8s.io/v1alpha4
      kind: Cluster

      # kubeadm patches set kube-apiserver flags for a predictable service-account issuer
      kubeadmConfigPatches:
        - |
          kind: ClusterConfiguration
          apiServer:
            extraArgs:
              service-account-issuer: "https://kubernetes.local"
              service-account-signing-key-file: "/etc/kubernetes/pki/sa.key"
              tls-cert-file: "/etc/kubernetes/pki/apiserver.crt"
              tls-private-key-file: "/etc/kubernetes/pki/apiserver.key"

      nodes:
        - role: control-plane
          extraPortMappings:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
            - containerPort: 443
              hostPort: 8443
              protocol: TCP
          extraMounts:
            - hostPath: /workspaces/kube-playground/.pki/out
              containerPath: /etc/kubernetes/pki
        - role: worker
