github:
  serverUrl: ""
  repository: ""
  user: ""
  token: ""

argocd:
  enabled: true
  configs:
    params:
      server.insecure: "true"
      server.basehref: "/argocd"
      server.rootpath: "/argocd"
      server.disable.auth: "true"

