---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xobjectstorages.example.org
spec:
  scope: LegacyCluster
  group: example.org
  names:
    kind: XObjectStorage
    plural: xobjectstorages
  claimNames:
    kind: ObjectStorage
    plural: objectstorages
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                location:
                  type: string
                  description: The location/region where the object storage will be created.
                  default: "{{ .Values.aws.defaultRegion }}"
              required: []
            status:
              type: object
              properties:
                bucketName:
                  type: string
                bucketArn:
                  type: string
          required: ["spec"]
