repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: bedag
    url: https://bedag.github.io/helm-charts

releases:
  - name: argo-cd
    namespace: argocd
    chart: argo/argo-cd
    createNamespace: true
    timeout: 300
    values:
      - configs:
          params:
            server.insecure: "true"
            server.basehref: "/argocd"
            server.rootpath: "/argocd"
            server.disable.auth: "true"
        server:
          ingress:
            enabled: true
            hostname: 'localhost'
            path: '/argocd'
            extraHosts:
              - name: '{{ requiredEnv "CODESPACE_NAME" }}-443.{{ requiredEnv "GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN" }}'
  - name: extra-resources
    namespace: argocd
    chart: bedag/raw
    values:
      - resources:
          - apiVersion: v1
            kind: Secret
            metadata:
              name: {{ requiredEnv "CODESPACE_NAME" }}
              labels:
                argocd.argoproj.io/secret-type: repository
            stringData:
              type: git
              url: '{{ requiredEnv "GITHUB_SERVER_URL" }}/{{ requiredEnv "GITHUB_REPOSITORY" }}'
              usernname: '{{ requiredEnv "GITHUB_USER" }}'
              password: '{{ requiredEnv "GITHUB_TOKEN" }}'
          - apiVersion: argoproj.io/v1alpha1
            kind: Application
            metadata:
              name: applications
              namespace: argocd
            spec:
              project: default
              source:
                repoURL: '{{ requiredEnv "GITHUB_SERVER_URL" }}/{{ requiredEnv "GITHUB_REPOSITORY" }}'
                targetRevision: HEAD
                path: application.d
              destination:
                server: https://kubernetes.default.svc
                namespace: argocd
              syncPolicy:
                automated: {}
