---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world
data:
  hello: world

---
apiVersion: pkg.crossplane.io/v1beta1
kind: Provider
metadata:
  name: aws
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:v2

---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: aws
spec:
  providerRef:
    name: aws
  extraProviderPackages:
    - xpkg.upbound.io/upbound/provider-aws-s3:v2

---
apiVersion: aws.m.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    secretRef:
      key: creds
      name: aws
      namespace: crossplane
    source: Secret
