---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  credentials:
    secretRef:
      key: creds
      name: aws
      namespace: crossplane
    source: Secret
