---
apiVersion: v1
kind: Secret
metadata:
  name: aws
stringData:
  creds: |
    [default]
    aws_access_key_id = {{ .Values.aws.accessKeyId }}
    aws_secret_access_key = {{ .Values.aws.secretAccessKey }}
